### ISSUE TITLE
UI upgrades - check out source for noscript (multi dom-level; only 1 refresh)

### ISSUE THREAD

**Issue by Astara** [RequestPolicy/requestpolicy#293]
2 things you need to pull in from noscript (he needs to pull in some of your code too, so don't feel I'm only picking on you! ;-)  ).

Specifically, 
1) when I select option to showme 3 domain segments (xxx.dom.tlc) vs. 2, it ignores
permission lists for top level 2-segments already in place.  I.e.
1A) if there is a 2 segment top domain in place, that permits, it should allow anything underneath it.  
1B) IMPORTANT: if there is a more refined URL (like www.xxx.com, under xxx.com), the more refined one **reverses** the sense of the higher level domain (it's an exception to the previous "permission rule")

1B*) -- this implies one would have to start with a policy of permit all or none, and that from there, the first domain you enter would flip the sense (even if it was 2 segments in a 0-segment permission domain...(the normal TLC case, as few people permit/prohibit com/biz/tv/org/net...etc).

Structured this way, people who want a black list can have it! .. i.e. by permit all @ top, then a new entry like "foo.org" would become a 'blacklisted site'.

---

This is a complication, but necessary (as well as unlikely):
if I add www.foo.org for blacklisting, then later add "foo.org", the add manager would need to say to user:
   "You currently have "www.foo.org", "ftp.foo.org" and "ntp.foo.org" <black
    (or white)>listed.  Adding foo.org will merge those subdomains into the
    new entry?  Continue with merge, OR stop add of "foo.org" and keep
    separate subdomains?

This way, it keeps the security lists 'minimal' and 'canonical'... you won't have overlapping permissions.

---

As it is now.. I'm screwed.... because your private page says google has tons of subdomains under google -- and I want to be able to selectively allow some -- but for MOST smaller sites, that isn't necessary -- so I need to have it pay attention to either 2nd or 3rd level domain segment -- 

I don't need the exception part so much as I need it to pay attention to 2-segment doms that are in place that allow all access to subdoms... (you see why I want the exception list -- because tehre will always be times when you want most of a site, but not maybe their "ad". subdomain...  ;-)...

---

The refresh thing is 'short' -- look at noscript... he doesn't refresh the page until you stop picking sites to allow.  So only 1 refresh is needed.

(sorry for including it in same, but I can submit it again separately (or you can copy this part to a new bug if it helps...)...

Astara...

**Comment by jsamuel** [comment]
I've taken a fresh approach to the UI in RP 1.0. I did try to make a traditional menu work for the new version but traditional menus are incapable of getting a good user experience here. The new menu system does allow you to add/remove multiple rules before a refresh. The refresh only happens when the menu is closed.

Version 1.0 doesn't currently give you options in the menu to whitelist/blacklist at different subdomain levels but the rule system does support this. Future versions can start adding more advanced information and options to the menu such as giving whitelist/blacklist rule options at different subdomain levels (configurable through preferences). For now, you can add rules for different domain levels manually through Manage Policy.

Version 1.0 defaults to allowing requests by default. You can switch back to a default-deny mode through Manage Policy > Default Policy. In a later alpha release I'll probably add a tab that opens on first install that lets users change this setting and a few others.

You can use the default-allow mode and have most of your rules be "block" rules. However, you can create exceptions by creating "allow" rules. The same is true for default-deny mode but in that case if there are both allow and block rules that apply to the request, then you will block the request.

If you want to try out 1.0, take a look here: https://www.requestpolicy.com/1.0.html

Thanks for your feedback. I'm going to go ahead and close this ticket but please do feel free to open new tickets about ways you'd like to see 1.0 improved and new options added.
