### ISSUE TITLE
Zotero content/snapshots blocked

### ISSUE THREAD

**Issue by jsamuel** [RequestPolicy/requestpolicy#52]
```
imported trac ticket
created: 2009-10-27 12:47:28
reporter: justin
```

fung0 [http://forums.mozillazine.org/viewtopic.php?p=7840995#p7840995 writes]:
  More importantly, 0.5.10 seems to eliminate a similar issue viewing my Zotero snapshots, with !RequestPolicy blocking all destinations in the local Zotero folder. My saved Zotero pages now look much better, though they still do suffer from a few missing pieces.

I need to test with Zotero to find/eliminate incompatibilities.

**Comment by jsamuel** [comment]
```
imported trac comment
created: 2011-01-07 11:57:47
author: justin
```

Some quick testing with Zotero shows it working fairly well. I didn't see any show-stoppers. What I noticed was that viewing saved zotero://attachment/[NUMBER] pages would would result in blocked cross-site requests from the saved page to various cross-site resources the page would have normally requested, though I don't know if some of these are requests to the same domain (I'm not sure off hand what zotero saves and what it doesn't --- my guess is that it saves content/resources from the same site but doesn't save cross-site content).

When viewing a saved page, the address bar would read zotero://attachment/[NUMBER]. The RP menu shows the origin as being either "attachment" when using "base domain" or "full domain" strictness and "zotero://attachment" when using "full address" strictness. Whitelisting does seem to work.

This all looks acceptable. If this is causing problems, then it's going to take a Zotero+RP user to point out what features of Zotero are broken or what is really annoying about this combination of extensions.

**Comment by beefstew** [comment]
I'm running RequestPolicy 0.5.27 and Zotero 4.0.8 in Firefox 21.0 on OS X 10.8.

When I try to view zotero://attachment/#### PDFs using the built-in PDF viewer, a progress bar quickly appears and completes, but then no PDF is displayed.

I using the "base domain" strictness setting and have tried adding a whitelist destination for attachment, zotero://attachment, zotero://, zotero -- all to no avail.

Viewing PDFs also doesn't work when I temporarily allow all requests using RequestPolicy, so maybe the problem lies with Zotero.

Does anyone else have this problem?

Useragent (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0)
